### ISSUE TITLE
Crash when dragging first child

### ISSUE THREAD

**Issue by deva666** [justasm/DragLinearLayout#37]
When you try to drag the first child of the layout a crash happens.
Stacktrace:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.jmedeisis.draglinearlayout.DragLinearLayout$DraggableChild.endExistingAnimation()' on a null object reference
                      at com.jmedeisis.draglinearlayout.DragLinearLayout.startDetectingDrag(DragLinearLayout.java:348)
                      at com.jmedeisis.draglinearlayout.DragLinearLayout.access$2200(DragLinearLayout.java:40)
                      at com.jmedeisis.draglinearlayout.DragLinearLayout$DragHandleOnTouchListener.onTouch(DragLinearLayout.java:701)
```
Version 1.0.0 and 1.1.0

**Comment by deva666** [comment]
Found the problem was some views that are not draggable got added and removed after adding draggable children.
